astra_db:
  collection_name: "prodassistant"

embedding_model:
  provider: "openai" 
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

sql_server:
  connection_string: 
      "DRIVER={ODBC Driver 18 for SQL Server};
      SERVER=20.213.152.181,1433;
      DATABASE=ADAMAS;
      UID=adamas;
      PWD=samada2002;
      TrustServerCertificate=yes;
      "
    

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048
  openai:
    provider: "openai"
    model_name: "gpt-4o"
    temperature: 0

security:
  SECRET_KEY: "24241sgdsg4352353425gghewgvgnkhtvcbn43643cvb"  # Change this!
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: 30

apiendpoint:
  base_url : "https://adamas.traccs.cloud:9000"
  from_email : "arshad@adamas.ner.au"
  from_name : "Arshad Abbas"